### ISSUE TITLE
Details Required

### ISSUE THREAD

**Issue by sandynigs** [mayankpathak19/Programming-Collective-Intelligence#1]
What features are required on the web applications?
Kindly elucidate the portion so that work can be done. Apologies in advance, I am a newbie, kindly bear with me

**Comment by mayankpathak19** [comment]
Since i leave it entirely up to you so you have the final say in this feature.
But some basic and minimalist features would be following views

- [ ] Result view which shows the result after the model has given predictions

- [ ] Initial view for selecting the user id for which recommendations need to be made

It should also consist of a model which is actually a database form of the movies.csv and ratings.csv file.

You have complete freedom to implement this in whichever way you want, using any web framework in python you are comfortable in.
